language: node_js
node_js:
  - "6"
sudo: required
dist: trusty
before_install:
- export DISPLAY=:99.0
before_script:
  - npm install -g gulp cordova ionic gulp-cli bower phantomjs
install:
  - npm install
script: 
  - gulp test
